In [3]:
import pandas as pd
import numpy as np
df = pd.read_csv('https://github.com/Anudeep2315/Employee-Retention-Model---Deep-Leanring/blob/master/HR_comma_sep.csv', sep=',')

In [4]:
df. head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years department  \
0                   3              0     1                      0      sales   
1                   6              0     1                      0      sales   
2                   4              0     1                      0      sales   
3                   5              0     1                      0      sales   
4                   3              0     1                      0      sales   

   salary  
0     low  
1  medium  
2  medium  
3     low  
4     low

In [5]:
df.isnull().sum()

satisfaction_level       0
last_evaluation          0
number_project           0
average_montly_hours     0
time_spend_company       0
Work_accident            0
left                     0
promotion_last_5years    0
department               0
salary                   0
dtype: int64

In [6]:
df.dtypes

satisfaction_level       float64
last_evaluation          float64
number_project             int64
average_montly_hours       int64
time_spend_company         int64
Work_accident              int64
left                       int64
promotion_last_5years      int64
department                object
salary                    object
dtype: object

We need to convert the convert the categorial data in to numeric data before feeding in to Keras

In [7]:
dummies = ['department','salary']
data = pd.get_dummies(df, columns = dummies, drop_first = True )
data.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years  \
0                   3              0     1                      0   
1                   6              0     1                      0   
2                   4              0     1                      0   
3                   5              0     1                      0   
4                   3              0     1                      0   

   department_RandD  department_accounting  department_hr  \
0                 0                      0              0   
1                 0                      0              0   
2                 0                      0              0   
3                 0                      0              0   
4                 0                      0              0   

   department_management  department_marketing  department_product_mng  \
0                      0                     0                       0   
1                      0                     0                       0   
2                      0                     0                       0   
3                      0                     0                       0   
4                      0                     0                       0   

   department_sales  department_support  department_technical  salary_low  \
0                 1                   0                     0           1   
1                 1                   0                     0           0   
2                 1                   0                     0           0   
3                 1                   0                     0           1   
4                 1                   0                     0           1   

   salary_medium  
0              0  
1              1  
2              1  
3              0  
4              0

X_train = Train data should not include the Criterion variable, we will take the values of criterion variable in to a y_train for comparing the results

In [8]:
x = data.drop(['left'], axis=1).values
y = data['left'].values
print("Employee details : ", x[0])
print("Employee left the company : ",y[0])

Employee details :  [  0.38   0.53   2.   157.     3.     0.     0.     0.     0.     0.
   0.     0.     0.     1.     0.     0.     1.     0.  ]
Employee left the company :  1


#### We are going to split the data between train and split.

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size = 0.2)

In [11]:
from sklearn.preprocessing import StandardScaler 

In [12]:
s = StandardScaler()
X_train = s.fit_transform(X_train)
X_test = s.fit_transform(X_test)

#### Let's Build a ANN model using keras

In [13]:
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [14]:
model = Sequential()
model.add(Dense(9,kernel_initializer = 'uniform', activation= 'relu', input_dim=18))
model.add(Dense(1, kernel_initializer = 'uniform', activation = 'sigmoid'))
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics=['accuracy'])

Instructions for updating:
Colocations handled automatically by placer.


In [15]:
model.fit(X_train, y_train, epochs = 10, batch_size= 15) 

Instructions for updating:
Use tf.cast instead.
Epoch 1/10
11999/11999 [==============================] - 1s 119us/step - loss: 0.4408 - acc: 0.8221
Epoch 2/10
11999/11999 [==============================] - 1s 82us/step - loss: 0.2433 - acc: 0.9192
Epoch 3/10
11999/11999 [==============================] - 1s 79us/step - loss: 0.1910 - acc: 0.9438
Epoch 4/10
11999/11999 [==============================] - 1s 95us/step - loss: 0.1731 - acc: 0.9492
Epoch 5/10
11999/11999 [==============================] - 1s 115us/step - loss: 0.1668 - acc: 0.9493
Epoch 6/10
11999/11999 [==============================] - 1s 119us/step - loss: 0.1635 - acc: 0.9516
Epoch 7/10
11999/11999 [==============================] - 1s 113us/step - loss: 0.1619 - acc: 0.9510
Epoch 8/10
11999/11999 [==============================] - 1s 113us/step - loss: 0.1608 - acc: 0.9523
Epoch 9/10
11999/11999 [==============================] - 1s 113us/step - loss: 0.1596 - acc: 0.9517
Epoch 10/10
11999/11999 [=====================

#### we have model accuracy of 95% which is great.<br>
Let's use the predict() method to use the model on X_test data

In [16]:
predicted_results = model.predict(X_test)

The Below predicted results of probablity of employee leaving the organisations based on each employee details

In [17]:
predicted_results
predicted_results = predicted_results>0.5 # returns TRUE if more than 0.5 else FALSE and makes it compatible for confusion matrix computation

In [18]:
print(predicted_results[0:5])
print(y_test[0:5])

[[False]
 [False]
 [False]
 [False]
 [ True]]
[0 0 0 0 1]


### Confusion Matrix of out prediction results

In [19]:
from sklearn.metrics import confusion_matrix
con_matrix = confusion_matrix(y_test,predicted_results)
con_matrix

array([[2210,   81],
       [  70,  639]], dtype=int64)

### Let's see if we can improve the model accuracy even more by implementing K-Fold Cross Validation.

keras enables you to implement K-fold cross-validation via the KerasClassifier wrapper. This wrapper is from scikit-learn cross-validation. You'll start by importing the cross_val_score cross-validation function and the KerasClassifier

In [20]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score

We will create a function ( that includes ANN model ) which will be passed as an argument to KerasClassifier

In [21]:
def make_classifier():
    model = Sequential()
    model.add(Dense(9,kernel_initializer = 'uniform', activation= 'relu', input_dim=18))
    model.add(Dense(1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics=['accuracy'])
    return model

In [22]:
model = KerasClassifier(build_fn = make_classifier, batch_size = 10, epochs =3)

We will use cross_val_score from sklearn to get the accuracies of each fold (12 folds )

In [23]:
accuracies = cross_val_score(estimator = model, X = X_train, y = y_train, cv = 12, n_jobs = -1)

In [24]:
accuracies

array([0.94799999, 0.93899999, 0.95499999, 0.95699999, 0.93499999,
       0.95399999, 0.92699999, 0.94699999, 0.94599999, 0.94399999,
       0.95299999, 0.89789789])

In [25]:
accuracy = accuracies.mean()
accuracy

0.9419081514122131

In [26]:
variance = accuracies.var()
variance

0.0002473245329163551

Since our model prediction accuracy is too good to believe ( something fishy!!!! )<br>
Let's implement Dropout regularisation to fight any overfitting that exists in the model learning.

<u>In neural networks, dropoutregularization is the technique that fights overfitting by adding a Dropout layer in your neural network. It has a rate parameter that indicates the number of neurons that will deactivate at each iteration. The process of deactivating nerurons is usually random<u/>

In [27]:
from keras.layers import Dropout

In [28]:
model = Sequential()
model.add(Dense(9,kernel_initializer = 'uniform', activation= 'relu', input_dim=18))
model.add(Dropout(rate=0.2))
model.add(Dense(1, kernel_initializer = 'uniform', activation = 'sigmoid'))
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics=['accuracy'])

Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


In [29]:
model.fit(X_train, y_train, epochs = 10, batch_size= 15) 

Epoch 1/10
11999/11999 [==============================] - 1s 124us/step - loss: 0.4653 - acc: 0.7996
Epoch 2/10
11999/11999 [==============================] - 1s 98us/step - loss: 0.2987 - acc: 0.8822
Epoch 3/10
11999/11999 [==============================] - 1s 101us/step - loss: 0.2526 - acc: 0.9039
Epoch 4/10
11999/11999 [==============================] - 1s 85us/step - loss: 0.2349 - acc: 0.9133
Epoch 5/10
11999/11999 [==============================] - 1s 84us/step - loss: 0.2266 - acc: 0.9167
Epoch 6/10
11999/11999 [==============================] - 1s 88us/step - loss: 0.2159 - acc: 0.9211
Epoch 7/10
11999/11999 [==============================] - 1s 88us/step - loss: 0.2165 - acc: 0.9211
Epoch 8/10
11999/11999 [==============================] - 1s 87us/step - loss: 0.2150 - acc: 0.9257
Epoch 9/10
11999/11999 [==============================] - 1s 85us/step - loss: 0.2103 - acc: 0.9237
Epoch 10/10
11999/11999 [==============================] - 1s 84us/step - loss: 0.2092 - acc: 0.92

In [30]:
predicted_results = model.predict(X_test)

The Below predicted results of probablity of employee leaving the organisations based on each employee details

In [31]:
predicted_results
predicted_results = predicted_results>0.5 # returns TRUE if more than 0.5 else FALSE and makes it compatible for confusion matrix computation

In [32]:
print(predicted_results[0:5])
print(y_test[0:5])

[[False]
 [False]
 [False]
 [False]
 [ True]]
[0 0 0 0 1]


### Confusion Matrix of our prediction results

In [33]:
from sklearn.metrics import confusion_matrix
con_matrix = confusion_matrix(y_test,predicted_results)
con_matrix

array([[2218,   73],
       [  74,  635]], dtype=int64)

### Hyperparameter Tuning

Grid search is a technique that you can use to experiment with different model parameters in order to obtain the ones that give you the best accuracy.

In [34]:
from sklearn.model_selection import GridSearchCV

In [35]:
def make_classifier(optimizer):
    model = Sequential()
    model.add(Dense(9,kernel_initializer = 'uniform', activation= 'relu', input_dim=18))
    model.add(Dense(1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    model.compile(optimizer = optimizer, loss = 'binary_crossentropy', metrics=['accuracy'])
    return model

In [36]:
model = KerasClassifier(build_fn = make_classifier)

Now Let's define different set of params to see which set of parameters are good in giving the best accuracy

In [37]:
params = {'batch_size':[25,35],
          'epochs':[4,6],
          'optimizer':['adam','rmsprop']
          }

Now define GridSearchCV function

In [38]:
optimization = GridSearchCV(estimator = model, param_grid = params, scoring = 'accuracy', cv=3)

In [39]:
optimization_model = optimization.fit(X_train, y_train)

Epoch 1/4
7999/7999 [==============================] - 1s 131us/step - loss: 0.5558 - acc: 0.7551
Epoch 2/4
7999/7999 [==============================] - 0s 45us/step - loss: 0.3795 - acc: 0.8136
Epoch 3/4
7999/7999 [==============================] - 0s 55us/step - loss: 0.3219 - acc: 0.8279
Epoch 4/4
7999/7999 [==============================] - 0s 55us/step - loss: 0.2906 - acc: 0.8327
Epoch 1/4
7999/7999 [==============================] - 1s 120us/step - loss: 0.5558 - acc: 0.7667
Epoch 2/4
7999/7999 [==============================] - 0s 44us/step - loss: 0.3594 - acc: 0.8510
Epoch 3/4
7999/7999 [==============================] - 0s 43us/step - loss: 0.2739 - acc: 0.9025
Epoch 4/4
7999/7999 [==============================] - 0s 44us/step - loss: 0.2264 - acc: 0.9264
Epoch 1/4
8000/8000 [==============================] - 1s 113us/step - loss: 0.5506 - acc: 0.7611
Epoch 2/4
8000/8000 [==============================] - 0s 45us/step - loss: 0.3702 - acc: 0.8034
Epoch 3/4
8000/8000 [======

Now that, we are done with running the model, Let's see which set of parameters are the best choice of params whcih gives best accuracy

In [41]:
Best_Params = optimization_model.best_params_
Best_Score = optimization_model.best_score_
print("Best_Params:", Best_Params)
print("Best_Score:", Best_Score)

Best_Params: {'batch_size': 25, 'epochs': 6, 'optimizer': 'adam'}
Best_Score: 0.92699391615968
